export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const ADD_SELECTED_IMAGE ='ADD_SELECTED_IMAGE';
export const REMOVE_SELECTED_IMAGE ='REMOVE_SELECTED_IMAGE';
export const ADD_TO_PENDING ='ADD_TO_PENDING';