export const AllPRODUCT_DETAILS=[
    {
        id:1,
        name:"Sustainable",
        price:"10000",
        tags:"null",
        disription:"Watch out this space for more details",
        image:require('../../assets/img1.jpg'),
        image2:require('../../assets/img2.jpg'),
        image3:require('../../assets/img1.jpg'),
        image4:require('../../assets/img2.jpg'),
        image5:require('../../assets/img2.jpg'),
    },
    {
        id:2,
        name:"Cotton",
        price:"20000",
        tags:"null",
        disription:"Watch out this space for more details",
        image:require('../../assets/img1.jpg'),
        image2:require('../../assets/img1.jpg'),
        image3:require('../../assets/img1.jpg'),
        image4:require('../../assets/img1.jpg'),
        image5:require('../../assets/img1.jpg'),

    },
    {
        id:3,
        name:"Premium",
        price:"30000",
        tags:"null",
        disription:"Watch out this space for more details",
        image:require('../../assets/img1.jpg'),
        image2:require('../../assets/img1.jpg'),
        image3:require('../../assets/img1.jpg'),
        image4:require('../../assets/img1.jpg'),
        image5:require('../../assets/img1.jpg'),

    },
    {
        id:4,
        name:"Premium",
        price:"40000",
        tags:"null",
        disription:"Watch out this space for more details",
        image:require('../../assets/img1.jpg'),
        image2:require('../../assets/img1.jpg'),
        image3:require('../../assets/img1.jpg'),
        image4:require('../../assets/img1.jpg'),
        image5:require('../../assets/img1.jpg'),

    },
    {
        id:5,
        name:"Premium",
        price:"50000",
        tags:"null",
        disription:"Watch out this space for more details",
        image:require('../../assets/img1.jpg'),
        image2:require('../../assets/img1.jpg'),
        image3:require('../../assets/img1.jpg'),
        image4:require('../../assets/img1.jpg'),
        image5:require('../../assets/img1.jpg'),

    },
    {
        id:6,
        name:"Vip",
        price:"60000",
        tags:"null",
        disription:"Watch out this space for more details",
        image:require('../../assets/img1.jpg'),
        image2:require('../../assets/img1.jpg'),
        image3:require('../../assets/img1.jpg'),
        image4:require('../../assets/img1.jpg'),
        image5:require('../../assets/img1.jpg'),

    },
];
